[project]
name = "cathaydidisdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.1",
]
